version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    # Let the Dockerfile handle the Angular workspace detection
    command: /bin/sh -c "npm install && ng serve --host 0.0.0.0"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/homeassistant
      - ENVIRONMENT=development

  linebot:
    build:
      context: .
      dockerfile: docker/linebot.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./LineBotAI:/app
    depends_on:
      - backend
    environment:
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - BACKEND_API_URL=http://backend:8000
      - DEBUG_MODE=true

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthome
    restart: always

volumes:
  postgres_data:
