version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY_SERVER_URL}/smarthomeassistantweb-frontend:1.0
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8000

  backend:
    image: ${DOCKER_REGISTRY_SERVER_URL}/smarthomeassistantweb-backend:1.0
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/smarthome
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=smarthome
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:1.0
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=smarthome
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  linebot:
    image: ${DOCKER_REGISTRY_SERVER_URL}/smarthomeassistantweb-linebot:1.0
    container_name: linebot
    restart: always
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres-data: