version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
    - NODE_ENV=development

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://localdev:localdev@db:5432/smart_home_assistant
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=smart_home_assistant
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localdev"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
