version: '3'

services:
  frontend:
    image: popo510691/homeassistant.frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network
      
  backend:
    image: popo510691/homeassistant.backend:1.0
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthome
      - ENVIRONMENT=development
    depends_on:
      - db
    restart: always
    networks:
      - app-network
      
  linebot:
    image: popo510691/homeassistant.linebot:1.0
    ports:
      - "5000:5000"
    environment:
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - BACKEND_API_URL=http://backend:8000
      - DEBUG_MODE=true
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthome
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
